config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users do
    get "/full_profile", to: "profiles#full_profile"
    patch "/full_profile", to: "profiles#full_profile_edit"
  end

  root to: "pages#home"

  resource :profiles, only: %i[show]
  resources :weights, only: %i[index new create show edit update destroy]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :user_params, only: :full_profile_edit

  def full_profile
    @user = current_user
  end

  def show
    @weight
  end

  def full_profile_edit
    @user = User.find(current_user.id)
    @user.assign_attributes(user_params)
    @weight = Weight.create(value: params[:user][:weight][:value])
    @user.weights << @weight
    if @user.save
      redirect_to profiles_path
    else
      render :full_profile
    end
  end

  private

  def user_params
    params.require(:user).permit(:height, :phone, :birthday, :gender, :photo)
  end
end

app/views/profiles/_BMI_bar.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-6 col">
      <% if current_user.imc_calc <= 16 %>
        <%= image_tag "bmi_cropped2/under16.png", class: "img-bmi shadow-lg" %>
      <% else %>
        <%= image_tag "bmi_cropped2/under16.png", class: "img-bmi-now opacity-25" %>
      <% end %>
    </div>

    <div class="col-xs-6 col">
      <% if (current_user.imc_calc > 16) && (current_user.imc_calc <= 17) %>
        <%= image_tag "bmi_cropped2/16 - 17.png", class: "img-bmi shadow-lg" %>
      <% else %>
        <%= image_tag "bmi_cropped2/16 - 17.png", class: "img-bmi-now opacity-25" %>
      <% end %>
    </div>

    <div class="col-xs-6 col">
      <% if (current_user.imc_calc > 17) && (current_user.imc_calc <= 18.5) %>
        <%= image_tag "bmi_cropped2/17 - 18.png", class: "img-bmi shadow-lg" %>
      <% else %>
        <%= image_tag "bmi_cropped2/17 - 18.png", class: "img-bmi-now opacity-25" %>
      <% end %>
    </div>

    <div class="col-xs-6 col">
      <% if (current_user.imc_calc > 18.5) && (current_user.imc_calc <= 25) %>
        <%= image_tag "bmi_cropped2/18 - 25.png", class: "img-bmi shadow-lg" %>
      <% else %>
        <%= image_tag "bmi_cropped2/18 - 25.png", class: "img-bmi-now opacity-25" %>
      <% end %>
    </div>

    <div class="col-xs-6 col">
      <% if (current_user.imc_calc > 25) && (current_user.imc_calc <= 30) %>
        <%= image_tag "bmi_cropped2/25 - 30.png", class: "img-bmi shadow-lg" %>
      <% else %>
        <%= image_tag "bmi_cropped2/25 - 30.png", class: "img-bmi-now opacity-25" %>
      <% end %>
    </div>

    <div class="col-xs-6 col">
      <% if (current_user.imc_calc > 30) && (current_user.imc_calc <= 35) %>
        <%= image_tag "bmi_cropped2/30 - 35.png", class: "img-bmi shadow-lg" %>
      <% else %>
        <%= image_tag "bmi_cropped2/30 - 35.png", class: "img-bmi-now opacity-25" %>
      <% end %>
    </div>

    <div class="col-xs-6 col">
      <% if (current_user.imc_calc > 35) && (current_user.imc_calc <= 40) %>
        <%= image_tag "bmi_cropped2/35 - 40.png", class: "img-bmi shadow-lg" %>
      <% else %>
        <%= image_tag "bmi_cropped2/35 - 40.png", class: "img-bmi-now opacity-25" %>
      <% end %>
    </div>

    <div class="col-xs-6 col">
      <% if current_user.imc_calc > 40 %>
        <%= image_tag "bmi_cropped2/Over40.png", class: "img-bmi shadow-lg" %>
      <% else %>
        <%= image_tag "bmi_cropped2/Over40.png", class: "img-bmi-now opacity-25" %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/_card.html.erb
<div class="card-index-weight mb-3" style="max-width: 540px; border-radius:5px; border: transparent;">
  <div class="d-flex flex-column g-0">

    <div class="w-100 card-full-posted-left">
      <%= render "profiles/carousel", weight: weight %>
    </div>

    <%= link_to weight_path(weight), class:"text-decoration-none" do %>

      <div class="w-100 card-full-posted-right">
        <div class="card-text-posted d-flex card-full-posted-right">

          <h3 class="text-decoration-none"><i class="fa-solid fa-dumbbell"></i>  <%= weight.value.to_i %>kg</h3>

            <p><strong><i class="fa-solid fa-calendar-days"></i>  <%= weight.created_at.strftime("%d/%b/%Y") %></strong></p>

            <% unless current_user.weights.size <= index +1 %>
            <% diff = current_user.weights.order(created_at: :desc)[index + 1].value - weight.value %>
              <% if diff > 0 %>
                <p><i class="fa-solid fa-arrow-down text-success"></i>   <%= (diff * (-1))  %>kg</p>
              <% else %>
                <p><i class="fa-solid fa-arrow-up text-danger"></i>   <%= (diff * (-1))  %>kg</p>
                <% end %>
            <% else %>
              <p>💪 beginning</p>
            <% end %>

        </div>
    <% end %>

    </div>

  </div>
</div>
<!--
Resolução do Roberto
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
  <div class="carousel-inner">
    <% current_user.weights.map { |weight| weight.photos }.flatten.each_with_index do | photo, index | %>
      <div class="carousel-item <%= 'active' if index.zero? %>">
        <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill  %>
      </div>
    <% end %>

  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
-->

app/views/profiles/_carousel.html.erb
<div id="carouselExampleIndicators<%= weight.id %>" class="carousel slide" data-bs-ride="true">
  <div class="carousel-inner">
    <% if weight.photos.empty? %>
      <div data-upload-id="myFirstImage">
        <img src="https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=MnwxfDB8MXxyYW5kb218MHx8Ym9keWJ1aWxkZXJ8fHx8fHwxNjY4ODY1NTEy&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=700" alt="" class="img-index-carousel">
      </div>
    <% else %>
        <% weight.photos.each_with_index do |photo, index| %>
          <div class="carousel-item resize-center <%= 'active' if index.zero? %> img-index-carousel">
            <%= cl_image_tag photo.key, class: "img-index-carousel resize-index", crop: :pad  %>
          </div>
        <% end %>
    <% end %>
  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators<%= weight.id %>" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators<%= weight.id %>" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

</div>

app/views/profiles/full_profile.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <h2 class="h1-log mt-4 mb-4"><span style="color:white">COMPLETE </span><span style="color:red">PROFILE</span></h2>
  </div>
  <div class="d-flex justify-content-center">
    <%= simple_form_for @user, url: user_full_profile_path, method: :patch do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs text-white">
      <%= f.input :phone, required: true, autofocus: true, input_html: { class: 'bg-white', class:"text-dark rounded-pill"  }  %>
      <%= f.input :birthday, :order => [:day, :month, :year], required: true, start_year: Date.today.year - 90,
                              end_year: Date.today.year - 12, input_html: { class: 'bg-white', class:"text-dark rounded-pill"  }  %>
      <%= f.input :height, label: "Height (centimeters)", required: true, autofocus: true, input_html: { min: '90', max: '230', class: 'bg-white', class:"text-dark rounded-pill"  }  %>
      <%= f.input :gender, collection: User::GENDERS, required: true, autofocus: true, input_html: { class: 'bg-white', class:"text-dark rounded-pill"  }  %>
      <%= f.input :photo, as: :file, input_html: { class: 'bg-white', class:"text-dark rounded-pill"  } %>
      <%= f.simple_fields_for :weight do |w| %>
        <%= w.input :value, as: :numeric %>
      <% end %>
    </div>
    <div class="form-actions d-grid gap-2 mt-4">
      <%= f.button :submit, "Update", class: "btn btn-outline-secondary text-white rounded-pill" %>
    </div>
  </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
      <div class="card-show d-flex justify-content-between row">
        <div class="text-center fixed-sidebar-container row col-sm-12 col-md-3">
          <div class="d-flex justify-content-center">
            <% if current_user.photo.key.nil? %>
              <%= image_tag "icon.jpg", width: 60, height: 60, class: "profile-pic shadow", 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= cl_image_tag(current_user.photo.key, width: 60, height: 60, class: "profile-pic shadow", 'aria-haspopup': true, 'aria-expanded': false) %>
            <% end %>
          </div>
          <div class="info-color d-flex justify-content-center">
            <ul class="list-group list-group-horizontal mb-3 mt-3">
              <div class="stat-subtext">Age
                <li class="list-group"><%= current_user.birthday.nil? ? 0 : ((Time.zone.now - current_user.birthday&.to_time) / 1.year.seconds).floor %>y/o</li>
                </div>
                <div class="linha-vertical"></div>
                <div class="stat-subtext">Weight
                  <li class="list-group"><%= current_user.weights.last&.value.to_i %>kg</li>
                </div>
                <div class="linha-vertical"></div>
                <div class="stat-subtext">Height
                  <li class="list-group"><%= (current_user.height.nil? ? 0 : (current_user.height))/100 %>m</li>
                </div>
              </div>
            </ul>
            <div>
            <%= link_to "Post New Weight", new_weight_path, class: "btn btn-outline-gray mb-2" %>
            </div>
          </div>
        <div class="col-sm-12 col-md-9 text-center">
          <h3>Ideal weight: <%= current_user&.ideal_weight.to_i %>kg</h3>
          <h3 class="">BMI: <%= current_user&.imc_calc unless current_user&.imc_calc.nil? %> (<%=  current_user&.imc_message unless current_user&.imc_message.nil? %>)</h3>
          <!--<h3><%=  current_user&.progress_from_min %></h3>
              </div>
            </ul>
            <%= link_to "Post a new weight", new_weight_path, class: "link-secondary mt-4" %>
          </div>
          <div class="col-9 text-center">
            <h3 class="">BMI: <%= current_user&.imc_calc unless current_user&.imc_calc.nil? %> - <%=  current_user&.imc_message unless current_user&.imc_message.nil? %> Ideal weight: <%= current_user&.ideal_weight %>kg</h3>
            <!--<h3><%=  current_user&.progress_from_min %></h3>
          <h3><%=  current_user&.progress_from_begin %></h3>!-->
          <br>
          <%= render "profiles/BMI_bar"%>
        </div>
      </div>
      <div class="card-show mt-3 d-flex justify-content-center">
        <div class="text-center w-100 p-3">
          <h2>Progress in Graph</h2>
          <h3 style="margin-top: 2%"> <%= line_chart current_user&.weights&.pluck(:created_at, :value),
          min: (current_user&.sort_weight&.first || 10) - 10,
          max: (current_user&.sort_weight&.last || -10) + 10,
          label: "Weight",
          suffix: " kg",
          colors: ["#ff0000"],
          empty: "Let's work out!"
          %> </h3>
        </div>
      </div>
      <div class="card-show mt-3 d-flex justify-content-center">
        <div class="text-center w-100 p-3">
          <h2>Progress in Photo</h2>
          <div>
            <%# ------------------------------------------------------ %>
            <div class="d-flex flex-wrap justify-content-evenly">
              <div class="p-3 card-progress">
                <div class="card-body-progress mb-2">
                  <h4 class="card-title-progress">In the beginning</h4>
                </div>
                <div id="carouselExampleInterval<%= current_user.weights.first.id %>" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-inner rounded">
                    <% if current_user.weights.first.photos.attached? %>
                      <% current_user.weights.first.photos.each_with_index do |photo, index| %>
                        <div class="carousel-item resize-center <%= 'active' if index.zero? %>">
                          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :pad, style:"border-radius:5px;", class:"d-block w-100 resize-photo-profile" %>
                        </div>
                      <% end %>
                    <% else %>
                      <div class="photo-unleash-currently d-block w-100" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=MnwxfDB8MXxyYW5kb218MHx8Ym9keWJ1aWxkZXJ8fHx8fHwxNjY4ODY1NTEy&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=700)"></div>
                    <% end %>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval<%= current_user.weights.first.id %>" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval<%= current_user.weights.first.id %>" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item font-blue"><i class="fa-solid fa-dumbbell"></i> <%= current_user.weights.first.value %> kg</li>
                  <li class="list-group-item font-blue"><i class="fa-solid fa-calendar-days"></i> <%= current_user.weights.first.created_at.strftime('%d/%b/%Y') %></li>
                  <%= link_to "Show", weight_path(current_user.weights.first.id), class: "btn-outline-red m-3 text-decoration-none" %>
                </ul>
              </div>
              <%# ------------------- %>
              <div class="p-3 card-progress">
                <div class="card-body-progress mb-2">
                  <h4 class="card-title-progress">Currently</h4>
                </div>
                <div id="carouselExampleInterval<%= current_user.weights.last.id %>" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-inner rounded">
                    <% if current_user.weights.last.photos.attached? %>
                      <% current_user.weights.last.photos.each_with_index do |photo, index| %>
                        <div class="carousel-item resize-center <%= 'active' if index.zero? %>">
                          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :pad, style:"border-radius:5px;", class:"d-block w-100 resize-photo-profile" %>
                        </div>
                      <% end %>
                    <% else %>
                      <div class="photo-unleash-currently d-block w-100" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=MnwxfDB8MXxyYW5kb218MHx8Ym9keWJ1aWxkZXJ8fHx8fHwxNjY4ODY1NTEy&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=700)"></div>
                    <% end %>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval<%= current_user.weights.last.id %>" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval<%= current_user.weights.last.id %>" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item font-blue"><i class="fa-solid fa-dumbbell"></i> <%= current_user.weights.last.value %> kg</li>
                  <li class="list-group-item font-blue"><i class="fa-solid fa-calendar-days"></i> <%= current_user.weights.last.created_at.strftime('%d/%b/%Y') %></li>
                  <%= link_to "Show", weight_path(current_user.weights.last.id), class: "btn-outline-red m-3 text-decoration-none"  %>
                </ul>
              </div>
              <%# ------------------------------------------------------ %>
            </div>
          </div>
        </div>
      </div>
  </div>
  <!--<script>
// window.addEventListener('locationchange', () => {
// …
// });
window.addEventListener('load', () => {
  const currentWeight = document.getElementById("current-weight");
  const percentage = <%= current_user.percentage %>;
  const leftValue = `calc(${percentage}% - ${currentWeight.offsetWidth / 2}px)`;
  currentWeight.style.left = leftValue;
});
</script>!-->