config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users do
    get "/full_profile", to: "profiles#full_profile"
    patch "/full_profile", to: "profiles#full_profile_edit"
  end

  root to: "pages#home"

  resource :profiles, only: %i[show]
  resources :weights, only: %i[index new create show edit update destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer navbar-fixed-bottom">
  <div class="d-flex justify-content-center">
    <%= image_tag "logotipo_branco.png", class: "footer-image" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-md navbar-dark bg-black navbar-lewagon mt-3 mb-3">
  <div class="container-nav-home">

    <% if user_signed_in? %>
      <%= link_to profiles_path, class: "navbar-brand" do %>
        <%= image_tag "Progresso Fit png9.png" %>
      <% end %>
    <% else %>
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "Progresso Fit png9.png" %>
      <% end %>
    <% end %>

  </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse container-nav-home navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="name foo"><%= "#{current_user.first_name}  #{current_user.last_name}" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
            <%# <%= cl_image_tag("IMAGE_WITH_FACE_ID", width: 150, height: 150, crop: :thumb, gravity: :face) %>
              <%= cl_image_tag(current_user.photo.key, width: 45, height: 45, crop: :thumb, gravity: :face, class: "rounded-circle dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% else %>
              <%= image_tag "icon.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Homepage", root_path, class: "dropdown-item" %>
              <%= link_to "My Timeline", profiles_path, class: "dropdown-item" %>
              <%= link_to "All Posts", weights_path, class: "dropdown-item" %>
              <%= link_to "Post New Weight", new_weight_path, class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <%# <li class="nav-item">
            <%= link_to "About us", new_user_session_path, class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_weights.html.erb
<div class="container">
  <div class="navbar navbar-expand-md navbar-dark bg-black navbar-lewagon mt-3 mb-3">
    <div class="container-nav">

      <% if user_signed_in? %>
        <%= link_to profiles_path, class: "navbar-brand" do %>
          <%= image_tag "Progresso Fit png9.png" %>
        <% end %>
      <% else %>
        <%= link_to "/", class: "navbar-brand" do %>
          <%= image_tag "Progresso Fit png9.png" %>
        <% end %>
      <% end %>

    </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse container-nav navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="name foo"><%= "#{current_user.first_name}  #{current_user.last_name}" %>
            </li>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
              <%# <%= cl_image_tag("IMAGE_WITH_FACE_ID", width: 150, height: 150, crop: :thumb, gravity: :face) %>
                <%= cl_image_tag(current_user.photo.key, width: 45, height: 45, crop: :thumb, gravity: :face, class: "rounded-circle dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
              <% else %>
                <%= image_tag "icon.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>

              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Homepage", root_path, class: "dropdown-item" %>
                <%= link_to "My Timeline", profiles_path, class: "dropdown-item" %>
                <%= link_to "All Posts", weights_path, class: "dropdown-item" %>
                <%= link_to "Post New Weight", new_weight_path, class: "dropdown-item" %>
                <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <%# <li class="nav-item">
              <%= link_to "About us", new_user_session_path, class: "nav-link" %>
            <%# </li> %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>