config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users do
    get "/full_profile", to: "profiles#full_profile"
    patch "/full_profile", to: "profiles#full_profile_edit"
  end

  root to: "pages#home"

  resource :profiles, only: %i[show]
  resources :weights, only: %i[index new create show edit update destroy]
end

app/models/weight.rb
class Weight < ApplicationRecord
  include PgSearch::Model

  attr_accessor :date

  pg_search_scope :search_by_value_and_created_at,
                  against: [:value, :created_at],
                  using: {
                    tsearch: { prefix: true }
                  }

  belongs_to :user
  has_many_attached :photos

  validates :value, presence: true
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :set_weight, only: %i[show edit update destroy]

  def index
    if params[:begin].present? && params[:end].present?
      # @weights = current_user.weights.search_by_value_and_created_at(params[:query])
      date_begin = Date.parse(params[:begin])
      date_end = Date.parse(params[:end])
      if date_begin > date_end
        flash[:alert] = "End date have to be greater than beginning date."
        redirect_to weights_path
      end
      @weights = current_user.weights.where("created_at BETWEEN ? AND ?", date_begin.beginning_of_day, date_end.end_of_day)
    elsif params[:begin].present?
      date_begin = Date.parse(params[:begin])
      @weights = current_user.weights.where("created_at >= ? ", date_begin.beginning_of_day)
    elsif params[:end].present?
      date_end = Date.parse(params[:end])
      @weights = current_user.weights.where("created_at <= ? ", date_end.end_of_day)
    else
      @weights = current_user.weights
    end
  end

  # def index
  #   if params.present?
      # @weights = Weight.where(:created_at ==  params[:search][:created_at])
      # sql_query = "value ILIKE :query OR created_at ILIKE :query"
      # @weight = Weight.where(sql_query, query: "%#{params[:query]}%")
      # @weights = Weight.where('DATE(created_at) = ?', params[:query])
      # @weights = Weight.search_by_value_and_created_at(value: params[:query])
  #   else
  #     @weights = Weight.all
  #   end
  # end
  def email_notification
    if User.weights.last&.value.where("created_at >= ?", 1.week.ago.utc)
      EmailNotificationMailer.with(weight: @weight).post_new_weight.deliver_later
    end
  end

  def new
    @weight = Weight.new
  end

  def create
    @weight = Weight.new(weight_params)
    @weight.user = current_user
    if @weight.save
      redirect_to weight_path(@weight)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @weight.update(weight_params)
      redirect_to weight_path(@weight)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @weight.destroy
    redirect_to profiles_path, status: :see_other
  end

  private

  def weight_params
    params.require(:weight).permit(:value, photos: [])
  end

  def set_weight
    @weight = Weight.find(params[:id])
  end
end

app/views/weights/edit.html.erb
<div class="container text-center mt-5">
  <div class="mx-auto" style="width: 500px;">
    <div class="new-weight-card-body rounded-4 border border-secondary">
      <h3 class="new-weight-card-title mt-4 text-red-pf">Keep track of your progress!</h3>
        <div class="d-flex justify-content-center" data-controller="weight-image">
          <p class="new-weight-card-text">
          <%= simple_form_for @weight do |f| %>
          <div class="row justify-content-center" style= "text-align: -webkit-center;">
            <div class="col-sm-12"><p class="m-2">Submit your current weight (kg)
              <%= f.input :value, input_html: { class: "input-weight" }, label: false %></div>
            </div>
          <%= f.input :photos, as: :file, input_html: { multiple: true, class: "input-photo", accept: "image/png, image/jpg, image/jpeg" } %>
          <div class="custom-file-container" data-upload-id="myFirstImage">
            <div class="photo-preview-weight mb-1 mt-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=MnwxfDB8MXxyYW5kb218MHx8Ym9keWJ1aWxkZXJ8fHx8fHwxNjY4ODY1NTEy&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=700)"></div>
          </div>
          <%= f.submit "No pain, no gain", class: "btn btn-outline-red btn-nopain mt-3 mb-4" %>
            <%# <div class="position-relative">
              <div class="position-absolute bottom-0 start-0 p-4 px-1">
                <%= link_to profiles_path, class: "text-decoration-none text-light" do %>
                  <%# <i class="fa-solid fa-left-long"></i>
                <% end %>
              <%# </div> %>
            <%# </div> %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/weights/index.html.erb
<div class="container">

  <%= form_tag weights_path, method: :get do %>
    <div class="row">
      <div class="search-form-control flex-column flex-sm-row d-flex justify-content-center">
        <div class="start-label text-white mt-1 mb-1">From</div>
          <div class="start-date-input mt-1 mb-1">
            <%= date_field_tag :begin,
                        params[:begin],
                        placeholder: "Start",
                        class: "form-control",
                        as: :date %>
          </div>
          <div class="end-label text-white mt-1 mb-1">Until</div>
          <div class="end-date-input mt-1 mb-1">
            <%= date_field_tag :end,
                        params[:end],
                        class: "form-control",
                        placeholder: "Find your previous weight",
                        as: :date %>
          </div>
          <%# <%= f.input :created_at, as: :date, html5: true %>
          <div class="button-search-date mt-1 mb-1">
            <button name="button" type="submit" class="btn btn-search">
              <i class="fas fa-search"></i> Search
            </button>
          </div>
      </div>
    </div>
  <% end %>
  <div class="row d-flex justify-content-center">
    <div class="col-sm-12">
      <% if @weights.count == 1 %>
        <div class="card-show mt-3 d-flex justify-content-center">
          <div class="text-center">
            <h3>Your Post</h3>
            <div class="row animate__animated animate__fadeIn" style="justify-content: center;">
              <% @weights.reverse.each do |weight| %>
                <div class="col-10 d-flex align-items-center mt-3">
                  <%# ----------------------------------- %>
                  <div class="card-index-weight mb-3" style="max-width: 540px; border-radius:5px; border: transparent;">
                    <div class="row g-0">
                      <div class="col-12 card-full-posted-left">
                        <%# ----------------------------------- %>
                        <div id="carouselExampleIndicators<%= weight.id %>" class="carousel slide" data-bs-ride="true">
                          <div class="carousel-inner">
                            <% if weight.photos.empty? %>
                              <div data-upload-id="myFirstImage">
                                <img src="https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=MnwxfDB8MXxyYW5kb218MHx8Ym9keWJ1aWxkZXJ8fHx8fHwxNjY4ODY1NTEy&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=700" alt="" class="img-index-carousel">
                              </div>
                            <% else %>
                              <% weight.photos.each_with_index do |photo, index| %>
                                <div class="carousel-item <%= 'active' if index.zero? %> img-index-carousel">
                                  <%= cl_image_tag photo.key, class: "img-index-carousel"  %>
                                </div>
                              <% end %>
                            <% end %>
                          </div>
                          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators<%= weight.id %>" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                          </button>
                          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators<%= weight.id %>" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                          </button>
                        </div>
                        <%# ----------------------------------- %>
                      </div>
                      <%= link_to weight_path(weight), class:"text-decoration-none" do %>
                        <div class="w-100 card-full-posted-right">
                          <div class="card-text-posted d-flex card-full-posted-right">
                            <h3 class="text-decoration-none"><i class="fa-solid fa-dumbbell"></i> <%= weight.value %></h3>
                            <div>
                              <p><strong><i class="fa-solid fa-calendar-days"></i>  <%= weight.created_at.strftime("%d/%b/%Y") %></strong></p>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <%# ----------------------------------- %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="card-show mt-3 d-flex justify-content-center">
        <div class="text-center">
          <h3>All Your Posts</h3>
          <div class="row animate__animated animate__fadeIn">
            <% @weights.order(created_at: :desc).each_with_index do |weight, index| %>
              <div class="col-sm-12 col-md-4 col-lg-3 d-flex align-items-center mt-3">
                <%= render(partial:"profiles/card", locals: { weight: weight, index: index }) %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>
<!--
<div class="container">
  <% current_user.weights.each do |weight| %>
    <div class="card-trip mt-3">
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
        <%# <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        </div> %>
        <div class="carousel-inner">
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
          <% if weight.photos.attached? %>
            <% weight.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= 'active' if index.zero? %>">
                <%= cl_image_tag photo.key, height: 400, width: 500, crop: :fill %>
              </div>
            <% end %>
          <% else %>
            <div class="photo-unleash" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=MnwxfDB8MXxyYW5kb218MHx8Ym9keWJ1aWxkZXJ8fHx8fHwxNjY4ODY1NTEy&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=700)"></div>
          <% end %>
        </div>
      </div>
      <div class="card-trip-infos">
        <div>
          <h2><strong><%= weight.value %>kg</strong></h2>
          <p><strong>Uploaded at <%= weight.created_at.strftime("%d/%b/%Y") %></strong></p>
        </div>
        <h2 class="card-trip-pricing"><%= link_to weight_path(weight), data: {turbo_method: :delete, turbo_confirm: "Are you sure that you want to delete the item#{weight.id}?"}, class: "text-decoration-none text-secondary" do %>
          <i class="fa-solid fa-trash opacity-75 link-secondary"></i>
        <% end %></h2>
        <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
      </div>
    </div>
  <% end %>
</div>
-->

app/views/weights/new.html.erb
<div class="container text-center mt-5">
  <div class="mx-auto" style="width: 500px;">
    <div class="new-weight-card-body rounded-4 border border-secondary">
      <h3 class="new-weight-card-title mt-4 text-red-pf">Keep track of your progress!</h3>
        <div class="d-flex justify-content-center" data-controller="weight-image">
          <p class="new-weight-card-text">
          <%= simple_form_for @weight do |f| %>
          <div class="row justify-content-center" style= "text-align: -webkit-center;">
            <div class="col-sm-12 container-input-weight"><p class="m-2">Submit your current weight (kg)
              <%= f.input :value, input_html: { class: "input-weight" }, label: false %></div>
            </div>
          <%= f.input :photos, as: :file, input_html: { multiple: true, class: "input-photo", accept: "image/png, image/jpg, image/jpeg" } %>
          <div class="custom-file-container" data-upload-id="myFirstImage">
            <div class="photo-preview-weight mb-1 mt-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=MnwxfDB8MXxyYW5kb218MHx8Ym9keWJ1aWxkZXJ8fHx8fHwxNjY4ODY1NTEy&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=700)"></div>
          </div>
          <%= f.submit "No pain, no gain", class: "btn btn-outline-red btn-nopain mt-3 mb-4" %>
            <div class="position-relative">
              <div class="position-absolute bottom-0 start-0 p-4 px-1">
                <%= link_to profiles_path, class: "text-decoration-none text-light" do %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/weights/show.html.erb
<div class="container d-flex justify-content-center">
  <div class="card-trip mt-3 border border-light border-opacity-75">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
      <%# <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      </div> %>
      <div class="carousel-inner">
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
        <% if @weight.photos.attached? %>
          <% @weight.photos.each_with_index do |photo, index| %>
            <div class="carousel-item resize-center <%= 'active' if index.zero? %>">
              <%= cl_image_tag photo.key, class: :resize, crop: :pad, style:"border-radius:5px;" %>
            </div>
          <% end %>
        <% else %>
          <div class="photo-unleash" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=MnwxfDB8MXxyYW5kb218MHx8Ym9keWJ1aWxkZXJ8fHx8fHwxNjY4ODY1NTEy&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=700)"></div>
        <% end %>
      </div>
    </div>
    <div class="card-trip-infos">
      <div class="mx-3"></div>
      <div class="d-flex flex-column align-items-center">
        <h2><i class="weight-icon fa-solid fa-dumbbell"></i>  <strong><%= @weight.value.to_i %>kg</strong></h2>
        <p><i class="date-icon fa-solid fa-calendar-days"></i>  <strong><%= @weight.created_at.strftime("%d/%b/%Y") %></strong></p>
      </div>
      <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
      <div class="edit-icon">
        <div class="dropdown d-flex justify-content-end">
          <button class="icon-edit fa-solid fa-ellipsis text-decoration-none text-light" href="#" data-bs-toggle="dropdown" aria-expanded="false"></button>
          <ul class="dropdown-menu text-center">
            <li><%= link_to "Edit Post", edit_weight_path(@weight), class: "dropdown-item" %></li>
            <li><%= link_to "Delete Post", weight_path(@weight), data: {turbo_method: :delete, turbo_confirm: "Are you sure that you want to delete the item#{@weight.id}?"}, class: "dropdown-item"%>
            </ul>
          </div>
        </div>
      </div>
      <%# <%= link_to profiles_path, class: "text-decoration-none text-light px-4" do %>
        <%# <i class="fa-solid fa-left-long mb-3"></i> %>
        <%# <% end %>
      </div>
    </div>